### ISSUE TITLE
Make home page user friendly by updating design and interactivity of the page 

### ISSUE THREAD

**Issue by ishita-43** [ishita-43/Blockchain-Based-Voting-System#11]
**Additional context**
Updating ui to make it user friendly and easy to navigate between different menus and options.

**Comment by ishita-43** [comment]
> 

> @ishita-43 please assign this issue to me i'll try to work on it

Assigned, you can start working

**Comment by ishita-43** [comment]
Ok, did you get any problem while working on this

**Comment by ShivRaiGithub** [comment]
Can I be assigned to this too ? Since  I will be working on migrating the code to Nextjs, this can be taken care of along the way.

**Comment by ishita-43** [comment]
Ok

**Comment by ShivRaiGithub** [comment]
Please mark this as completed. Thank you.
