### ISSUE TITLE
Foundry instead of Ganache/Truffle

### ISSUE THREAD

**Issue by ShivRaiGithub** [ishita-43/Blockchain-Based-Voting-System#15]
**Is your feature request related to a problem? Please describe.**
Ganache and Truffle are less used nowadays compared to Hardhat and Foundry. 

**Describe the solution you'd like**
I would to transfer the contract code on Foundry as it is faster than Hardhat and also provides various tools for creation, testing, and deploying solidity contracts.

**Describe alternatives you've considered**
Hardhat can be used instead of Foundry.

**Additional context**
I am able to find the file for Migrations.sol but unable to find Vote.sol. Please provide a link to that file too. Thank you.

**Comment by ishita-43** [comment]
After migrating the voting file is converted to voting.json

**Comment by ShivRaiGithub** [comment]
![image](https://github.com/user-attachments/assets/2918b701-0431-48ea-920b-0612ee5cf92e)
I get what you are saying but for foundry I will need the Vote.sol file which isn't present in the contracts folder.

**Comment by ishita-43** [comment]
Done
